ARDUINO_DIR=../../bin/arduino
ARDMK_DIR=../../Arduino-Makefile
AVR_TOOLS_DIR=../../bin/avr
AVRDUDE_CONF=$(AVR_TOOLS_DIR)/etc/avrdude.conf
USER_LIB_PATH=../libraries
ARDUINO_SKETCHBOOK=../
BOARD_TAG    = uno
ARDUINO_LIBS =

include $(ARDMK_DIR)/Arduino.mk

