ARDUINO_DIR=../tools/arduino
ARDMK_DIR=../tools/Arduino-Makefile
AVR_TOOLS_DIR=../tools/avr
AVRDUDE_CONF=$(AVR_TOOLS_DIR)/etc/avrdude.conf
USER_LIB_PATH=../libraries
ARDUINO_SKETCHBOOK=../
BOARD_TAG    = uno
ARDUINO_LIBS =

include $(ARDMK_DIR)/Arduino.mk

